### ISSUE TITLE
Test openedx-filters on Ubuntu 24.04

### ISSUE THREAD

**Issue by feanil** [openedx/openedx-filters#206]
This repository is using Ubuntu 20.04 for testing. That version of Ubuntu will be out of support before Teak. Therefore this repo needs to be updated to testing with Ubuntu 24.04 before Sumac is cut to allow everyone sufficient time to switch to the new version.

Update this repository to test with Ubuntu 24.04 so that we can make the switch.

- [ ] Tests are run and passing on Ubuntu 20.04 and 24.04
- [ ] If major changes were needed and this is a library, a new version is published to PyPI or NPM

Note: In some cases, it may not make sense to test with both the old and the new version.  For example, if the workflow is running linting or publishing to a package manager.  In these cases, simply update the workflow to run on the newer version or opt to set it to `ubuntu-latest` instead if it doesn't matter what version it's running on.  If you're unsure, reach out to the maintenance working group in [#wg-maintenance](https://openedx.slack.com/archives/C03R320AFJP) in slack for guidance.

Known affected workflow files:

- .github/workflows/pypi-publish.yml
- .github/workflows/ci.yml

**Comment by mariajgrimaldi** [comment]
I dropped ubuntu 20.04 in all workflows since we're publishing to a package manager using ubuntu 24.04.

**Comment by Ian2012** [comment]
@feanil shouldn't it be `ubuntu-latest` as decided in this discussion: https://github.com/openedx/platform-roadmap/issues/377?

**Comment by mariajgrimaldi** [comment]
@Ian2012: thank you. I completely missed the details of the discussion. I'll be updating the PRs.

**Comment by feanil** [comment]
Awesome, thanks for taking care of this! Yes, hopefully with ubuntu-latest, we won't have to do much more of this kind of maintenance in the future.
