### ISSUE TITLE
Maintainership bots setup

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-filters#40]
### Description
Bots that help with maintenance work must be correctly configured and working. Bots like:

- [x] Dependency bot running at least weekly
- [x] Auto branch deletion
- [ ] Any other useful bot

Objective: avoid technical debt

**Comment by felipemontoya** [comment]
@mariajgrimaldi I was updating some of the columns in https://openedx.atlassian.net/wiki/spaces/COMM/pages/3663233055/Cumulative+Maintainer+Responsibilities when I noticed this open issue.

We already have the dependecy bot running weekly. Are we planning to include any other bot? Can we close this as "completed"?
